// AUTO-GENERATED from an "Approved Lumin Lenders" CSV export.
// Do not edit by hand — regenerate with: python3 scripts/parse_lenders.py <csv>

export interface Lender {
  /** Raw section key from the sheet (stable identifier). */
  category: string
  /** Human-friendly section label for chips/headers. */
  categoryLabel: string
  lender: string
  /** Set up in Arive? 'Yes' | 'No' | 'off' | '' (raw from sheet). */
  inArive: string
  contact: string
  phone: string
  email: string
  /** Eligibility badges that were marked for this lender. */
  products: string[]
  /** Min FICO (for 2nds: "<nq> NQ / <fd> Full"). */
  minFico: string
  /** Comp — LPC/BPC. */
  comp: string
  notes: string
}

export const LENDER_SECTIONS: { key: string; label: string }[] = [
  { key: "Agency/Jumbo", label: "Agency / Jumbo" },
  { key: "500-580 FHA/VA Govie Lenders", label: "500-580 Govie" },
  { key: "NON-QM", label: "Non-QM" },
  { key: "No Income/No Ratio", label: "No Income / No Ratio" },
  { key: "Agency 2nds and Non-QM 2nds", label: "2nds (Agency & Non-QM)" },
  { key: "Private Money Lenders (Max 55-65% LTV)", label: "Private Money" },
  { key: "Bridge Loans (Buy B4 Sell)", label: "Bridge (Buy-B4-Sell)" },
  { key: "Home Equity Conversion Mortgage (Reverse)", label: "Reverse (HECM)" },
  { key: "SBA Loans", label: "SBA" },
  { key: "Home Equity Investments", label: "Home Equity Investment" },
]

export const LENDERS: Lender[] = [
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "Rocket Mortgage (CORR Conv/VA)", "inArive": "Yes", "contact": "Geoff Samet", "phone": "313-751-9795", "email": "geoffsamet@rocketmortgage.com", "products": ["CONV", "VA", "FHA", "Jumbo"], "minFico": "620", "comp": "2.0%/3.0%", "notes": "580 overlay on conventional loans"},
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "A Mortgage Boutique (CORR Conv/VA)", "inArive": "No", "contact": "Fuzz Heidari", "phone": "818-968-4887", "email": "fuzz.heidari@amortgageboutique.com", "products": ["CONV", "VA", "FHA"], "minFico": "580", "comp": "2.75%", "notes": "Priced lower than Rocket and will do pricing exceptions. They have aggressive non qm pricing as well"},
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "Mega Capital Funding (CORR Conv/VA)", "inArive": "Yes", "contact": "Jeff Bartley", "phone": "858-776-5984", "email": "jeff@mcfunding.com", "products": ["CONV", "VA", "FHA", "Jumbo"], "minFico": "600", "comp": "2.75%", "notes": "A Paper, smooth process, KILLER pricing. 640 Conv, 620 VA, 600 FHA"},
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "NewRez", "inArive": "Yes", "contact": "Zachary Carr", "phone": "947-218-3192", "email": "zachary.carr@newrez.com", "products": ["CONV", "VA", "FHA", "<580"], "minFico": "580", "comp": "2.75%", "notes": "Great AE. NonQM DSCR,Bank Stmt, Smart Edge (full doc)-non warrantble, asset qualifer, LLPA discounted. Most Military Friendly. REZ CLUB--more aggressive pricing 3 loans a QTR. waive EPOs. (cannot add margin)."},
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "PennyMac", "inArive": "Yes", "contact": "Derek Conrad", "phone": "206-778-8969", "email": "derek.conrad@pennymac.com", "products": ["CONV", "VA", "FHA", "Jumbo"], "minFico": "620", "comp": "2.75%", "notes": ""},
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "Freedom Mortgage Corporation", "inArive": "Yes", "contact": "Neiko Basile", "phone": "310-871-5923", "email": "neiko.basile@freedommortgage.com", "products": ["VA", "FHA", "<580", "Jumbo"], "minFico": "620", "comp": "2.75%", "notes": "Min 580 for FHA/VA. service govies (max 50% dti on VA MUW) does not service conv. 400K+ priced well"},
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "Kind Lending (CORR Conv & Non QM)", "inArive": "Yes", "contact": "Manuel Lozano", "phone": "714-932-9967", "email": "mlozano@kindlending.com", "products": ["CONV", "VA", "FHA", "Jumbo"], "minFico": "620", "comp": "2.75%", "notes": "Competitive alternative to all products"},
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "Orion Lending", "inArive": "Yes", "contact": "Jason Brennan", "phone": "714-785-8686", "email": "jbrennan@orionlending.com", "products": ["CONV", "VA", "FHA", "<580"], "minFico": "550", "comp": "2.75%", "notes": "PHYSICIAN LOANS!! Have great DPA purchase programs and good govie loans."},
  {"category": "Agency/Jumbo", "categoryLabel": "Agency / Jumbo", "lender": "Union Home Mortgage (CORR Conv & Non QM)", "inArive": "off", "contact": "Jennifer Martinez", "phone": "619-502-0377", "email": "jmartinez@uhm.com", "products": ["CONV", "VA", "FHA", "Jumbo"], "minFico": "620", "comp": "2.75%", "notes": ""},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "Cardinal Financial", "inArive": "No", "contact": "Ryan Kolp", "phone": "313-402-8081", "email": "ryan.kolp@cardinalfinancial.com", "products": ["CONV", "VA", "FHA", "<580"], "minFico": "550", "comp": "2.75%", "notes": "550 govy loans, non qm loans, 2nds (no helocs)"},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "Nations Direct Mortgage", "inArive": "No", "contact": "Justin Simpers", "phone": "949 310 3750", "email": "js@mydnm.com", "products": ["CONV", "VA", "FHA", "<580"], "minFico": "550", "comp": "2.75%", "notes": "THEY ALLOW 2X 30 DAY LATES ON MANUAL UW"},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "NewRez", "inArive": "Yes", "contact": "Zachary Carr", "phone": "947-218-3192", "email": "zachary.carr@newrez.com", "products": ["VA", "FHA", "<580"], "minFico": "580", "comp": "2.75%", "notes": "NonQM DSCR,Bank Stmt, Smart Edge (full doc)-non warrantble, asset qualifer, LLPA discounted. Most Military Friendly. REZ CLUB--more aggressive pricing 3 loans a QTR. waive EPOs. (cannot add margin)."},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "Freedom Mortgage Corporation", "inArive": "Yes", "contact": "Neiko Basile", "phone": "310-871-5923", "email": "neiko.basile@freedommortgage.com", "products": ["VA", "FHA", "<580", "Jumbo"], "minFico": "570", "comp": "2.75%", "notes": "min 570 for VA/580 FHA. service govies (max 50% dti on VA MUW) does not service conv. 400K+ priced well"},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "Plaza Home Mortgage", "inArive": "Yes", "contact": "Mark Boleky", "phone": "904-344-3528", "email": "mark.boleky@plazahomemortgage.com", "products": ["CONV", "VA", "FHA", "<580"], "minFico": "550", "comp": "2.75%", "notes": ""},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "SunWest Mortgage (CORR Conv & Non QM)", "inArive": "No", "contact": "Suresh Choudhary", "phone": "562-740-8544", "email": "sureshc@swmc.com", "products": ["CONV", "VA", "FHA", "<580", "Jumbo"], "minFico": "500", "comp": "2.75%", "notes": ""},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "Equity Prime Mortgage", "inArive": "Yes", "contact": "Johnny Salerno", "phone": "630-624-0684", "email": "jsalerno@epm.net", "products": ["CONV", "VA", "FHA", "<580"], "minFico": "500", "comp": "2.75%", "notes": ""},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "Loan United (CORR Conv/VA)", "inArive": "Yes", "contact": "William Matiz", "phone": "800-258-7520 X 256", "email": "wmatiz@loanunited.com", "products": ["CONV", "VA", "FHA", "<580"], "minFico": "500", "comp": "2.75%", "notes": "IF CLIENT PAYS OFF THEIR LOAN OR MISSSES A PAYMENT WITHIN 6 MONTHS, IT TRIGGERS EPO. subprime borrowers good for 500-580 fico clients. Better process than Sunwest and EPM."},
  {"category": "500-580 FHA/VA Govie Lenders", "categoryLabel": "500-580 Govie", "lender": "Brokers First Funding (BFF)", "inArive": "No", "contact": "Nina Nguyen", "phone": "949 -307-4122", "email": "nnguyen@bffws.com", "products": ["CONV", "VA", "FHA", "<580", "Jumbo"], "minFico": "500", "comp": "2.75%", "notes": "Pricing great about 580+ or 620+. Can price match if needed. Amazing USDA program with their underwriting/process."},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "AmWest Funding Corp", "inArive": "No", "contact": "Alvaro Rodriguez", "phone": "714-706-8089", "email": "alvaro.rodriguez@amwestfunding.com", "products": ["CONV", "VA", "FHA", "Jumbo"], "minFico": "620", "comp": "2.75%", "notes": "Super competitive non qm and 2nd mortgage pricing"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Forward Lending (Loan Stream)", "inArive": "No", "contact": "Chris Calderon", "phone": "818-926-7078", "email": "ccalderon@forwardlendingmtg.com", "products": ["CONV", "VA", "FHA"], "minFico": "620", "comp": "2.75%", "notes": "Solid AE. Loans with lates and derogs. Good option for 600-600 fico. Good pricing with 660+ fico ."},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "HomeXpress Mortgage", "inArive": "No", "contact": "Sara Walker", "phone": "714-742-9911", "email": "swalker@homexmortgage.com", "products": ["CONV", "VA", "FHA"], "minFico": "620", "comp": "2.75%", "notes": "Great AE and team. Smooth process with solid pricing for higher LTVs"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Champions Funding", "inArive": "No", "contact": "Monica Mullen", "phone": "480-678-0381", "email": "monica.mullen@champstpo.com", "products": [], "minFico": "620", "comp": "2.75%", "notes": "Offers Community loan - No income docs required"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Change Mortgage", "inArive": "No", "contact": "Chris Mobasser", "phone": "949-584-0489", "email": "cmobasser@changemtg.com", "products": [], "minFico": "640", "comp": "2.75%", "notes": "Offers Community loan - No income docs required. Rough process and bad communication"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Mega Capital Funding", "inArive": "Yes", "contact": "Jeff Bartley", "phone": "858-776-5984", "email": "jeff@mcfunding.com", "products": ["CONV", "VA", "FHA", "Jumbo"], "minFico": "660", "comp": "2.75%", "notes": "A Paper, smooth process, KILLER pricing. 640 Conv, 620 VA, 600 FHA"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Newfi Lending", "inArive": "Yes", "contact": "Pete Bember", "phone": "770-906-7178", "email": "pbember@newfi.com", "products": [], "minFico": "620", "comp": "2.75%", "notes": "Solid HELOAN Pricing"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "The Loan Store (CORR Conv & Non QM)", "inArive": "Yes", "contact": "Devin Matthews", "phone": "214-729-3563", "email": "dmathews@theloanstore.com", "products": [], "minFico": "", "comp": "2.75%", "notes": "Bridge loans. Buy before sell loans. FHA Simply Solar (with approval)"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "LenderMac", "inArive": "Yes", "contact": "Sun Han", "phone": "213-507-6411", "email": "sun.han@lendermac.com", "products": [], "minFico": "650", "comp": "2.75%", "notes": "Competitive alternative to Non-QM products"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "New Wave Lending", "inArive": "No", "contact": "Queenie Zhao", "phone": "626-977-6665", "email": "queenie.zhao@newwavelending.com", "products": [], "minFico": "", "comp": "2.75%", "notes": ""},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Kind Lending", "inArive": "Yes", "contact": "Brandi Lozano", "phone": "714-400-7926", "email": "blozano@kindlending.com", "products": ["CONV", "VA", "FHA", "Jumbo"], "minFico": "600", "comp": "2.75%", "notes": "Competitive alternative to all products"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "NexBank (CORR Conv/VA)", "inArive": "No", "contact": "Lyndsey Madsen", "phone": "925-324-5511", "email": "lyndsey.madsen@nexbank.com", "products": [], "minFico": "", "comp": "2.75%", "notes": ""},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Symmetry Lending", "inArive": "No", "contact": "Bob Brenseke", "phone": "310-497-9463", "email": "bob.brenseke@symmetrylending.com", "products": [], "minFico": "", "comp": "2.75%", "notes": ""},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Jet Mortgage", "inArive": "Yes", "contact": "Jared Hilton", "phone": "469-733-5352", "email": "", "products": ["CONV", "VA", "FHA"], "minFico": "580", "comp": "2.75%", "notes": ""},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "LendSure", "inArive": "No", "contact": "Aaron Winer", "phone": "858-524-3887", "email": "awiner@lendsure.com", "products": [], "minFico": "640", "comp": "2.75%", "notes": "DSCR minimum FICO 660 up to 5-10 unit program. Solid Bank Statement and Asset Depletion programs. Other: Fix/Flip, Ground Up Construction, Bridge, and less than 1 YR SE program"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Brokers First Funding (BFF)", "inArive": "No", "contact": "Lito Gonzalez", "phone": "214-909-2648", "email": "lgonzalez@bffws.com", "products": ["CONV", "VA", "FHA", "<580", "Jumbo"], "minFico": "620", "comp": "", "notes": "Primary wage earner FICO will be used for bank statement, Investement properties w/PPP can be treated as business purpose. Cross Coll DSCR. allows non warrentable condos."},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "FundLoans", "inArive": "No", "contact": "Mitch Dempster", "phone": "858-275-6456", "email": "mdempster@fundloans.com", "products": ["Jumbo"], "minFico": "660", "comp": "", "notes": "Assistant Living Financing (lend on residential)"},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Deephaven Mortgage", "inArive": "", "contact": "Mike Wilson", "phone": "760-271-6463", "email": "mwilson@deephavenmortgage.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "Cake Mortgage", "inArive": "No", "contact": "Contessa Noel", "phone": "510-4107574", "email": "contessa.noel@cakehome.com", "products": [], "minFico": "", "comp": "2.75%", "notes": ""},
  {"category": "NON-QM", "categoryLabel": "Non-QM", "lender": "ACRA", "inArive": "", "contact": "Mario Bolanos", "phone": "949-620-3748", "email": "mario.bolanos@acralending.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "No Income/No Ratio", "categoryLabel": "No Income / No Ratio", "lender": "Champions Funding", "inArive": "No", "contact": "Monica Mullen", "phone": "480-678-0381", "email": "monica.mullen@champstpo.com", "products": [], "minFico": "620", "comp": "2.75%", "notes": "Offers Community loan - No income docs required"},
  {"category": "No Income/No Ratio", "categoryLabel": "No Income / No Ratio", "lender": "Change Mortgage", "inArive": "No", "contact": "Chris Mobasser", "phone": "949-423-6805", "email": "cmobasser@changemtg.com", "products": [], "minFico": "680", "comp": "2.75%", "notes": "Offers Community loan - No income docs required. Rough process and bad communication"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Figure Lending (CORR)", "inArive": "No", "contact": "Rebekah Lanning", "phone": "888-871-9744", "email": "whitelabel-support@figure.com / rlanning@figure.com", "products": ["Non-QM 2nd", "Piggyback 2nd"], "minFico": "600 Full", "comp": "2.00%", "notes": "Allows Business bank statements now. Min 600 FICO, 15k min loan, additional draws $500, min 10% balance req for 4 months for EPO."},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "NFTY Lead Bank", "inArive": "No", "contact": "Alex Laitamaki", "phone": "908-294-1290", "email": "alex.laitamaki@nftydoor.com", "products": ["Non-QM 2nd"], "minFico": "", "comp": "2.50%", "notes": "Loan Amount ot $750K 5yr Draw IO + 25yr term(TN 5yr IO + 10yr term | minimum 75% disbursed at closing  [Additional notes (verify owner): Min 640, 75% draw closing, addition draw $1000 and NO EPO- Help Line 844-975-5150 · HELOCs. Licensed all states EXCEPT: AK, HI, ID, MA, MO, ND, NY, SD, WV, WY · Good for piggyback 2nds for purchase. Also has a 10 year Draw 40 year I/O Fico needs to be above 700 · Competitive alternative to all products]"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "REMN/HELIX (6.15.2026)", "inArive": "Yes", "contact": "Julia Murphy", "phone": "201-446-9275", "email": "jmurphy@remn.com", "products": ["Agency", "Piggyback 2nd"], "minFico": "640 Full", "comp": "2.00%", "notes": "200+50bps / Helix can lend on properties currently listed for sale or listed within the last sixty (60) days except in the following states: DC, IL, IN, IA, LA, ME, NC, PA, RI, TN, TX, VT, WA"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Kind Lending", "inArive": "Yes", "contact": "Brandi Lozano", "phone": "714-400-7926", "email": "blozano@kindlending.com", "products": ["Agency", "Piggyback 2nd"], "minFico": "", "comp": "2.75%", "notes": "A Paper, smooth process, KILLER pricing. 640 Conv, 620 VA, 600 FHA. BS Closed-end seconds"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Rocket Mortgage", "inArive": "Yes", "contact": "Geoff Samet", "phone": "313-751-9795", "email": "geoffsamet@rocketmortgage.com", "products": ["Agency"], "minFico": "", "comp": "2.00%", "notes": "Solid HELOAN Pricing"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Mega Capital Funding", "inArive": "Yes", "contact": "Jeff Bartley", "phone": "858-776-5984", "email": "jeff@mcfunding.com", "products": ["Agency", "Non-QM 2nd", "HELOAN"], "minFico": "x NQ / 660 Full", "comp": "2.75%", "notes": "THEY ALLOW 2X 30 DAY LATES ON MANUAL UW. Will allow AVM on <$250K CES even on alt-doc"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Newfi Lending", "inArive": "Yes", "contact": "Pete Bember", "phone": "770-906-7178", "email": "pbember@newfi.com", "products": ["Agency", "Non-QM 2nd", "HELOAN"], "minFico": "660 NQ", "comp": "2.75%", "notes": "Competitive alternative to Non-QM products"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Nations Direct Mortgage", "inArive": "No", "contact": "Marsha Curry", "phone": "714-325-7140", "email": "mcurry@myndm.com", "products": ["Non-QM 2nd", "HELOAN"], "minFico": "660 NQ", "comp": "2.75%", "notes": "Super competitive non qm and 2nd mortgage pricing"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "LenderMac", "inArive": "Yes", "contact": "Sun Han", "phone": "213-507-6411", "email": "sun.han@lendermac.com", "products": ["Agency", "HELOAN"], "minFico": "680 NQ", "comp": "2.75%", "notes": "Solid AE. Loans with lates and derogs. Good option for 600-600 fico. Good pricing with 680+ fico . 10-YR Draws and 100% payback draw within 5-10 business days"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "AmWest Funding Corp", "inArive": "No", "contact": "Alvaro Rodriguez", "phone": "714-706-8089", "email": "alvaro.rodriguez@amwestfunding.com", "products": ["Agency", "Non-QM 2nd"], "minFico": "660 NQ / 680 Full", "comp": "2.75%", "notes": "DSCR, Bank Statement, Full Doc, P&L, 1099, WVOE Only 2nds"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Foward Lending (Loan Stream)", "inArive": "No", "contact": "Chris Calderon", "phone": "818-926-7078", "email": "ccalderon@forwardlendingmtg.com", "products": ["Agency", "Non-QM 2nd", "HELOAN"], "minFico": "660 NQ / Do Not Use Full", "comp": "2.75%", "notes": "no EPO and they pull their own credit. 10 draw period. Up to $500k. Bank statements okay if business is 100% owned. Up to 4% comp."},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Symmetry Lending", "inArive": "No", "contact": "Bob Brenseke", "phone": "310-497-9463", "email": "bob.brenseke@symmetrylending.com", "products": [], "minFico": "", "comp": "2.75%", "notes": "full doc, bank statements, P &L and DSCR doc types; CLTV 90%"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Jet Mortgage", "inArive": "Yes", "contact": "Jared Hilton", "phone": "469-733-5352", "email": "jared.hilton@jetmortgage.com", "products": ["Agency", "Non-QM 2nd", "HELOAN"], "minFico": "660 NQ", "comp": "2.75%", "notes": "Qualify with bank statements, P&L, full doc, 1099 only, or WVOE."},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Quorum FCU (Rehab, Regular Heloc Land Loans)", "inArive": "No", "contact": "Mark Panella", "phone": "925-519-6734", "email": "mark.panella@quorumfcu.org", "products": ["Agency"], "minFico": "", "comp": "2.75%", "notes": ""},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Brokers First Funding (BFF)", "inArive": "No", "contact": "Nina Nguyen", "phone": "949-307-4122", "email": "nnguyen@bffws.com", "products": ["Non-QM 2nd", "HELOAN"], "minFico": "660 NQ", "comp": "", "notes": ""},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "FundLoans", "inArive": "No", "contact": "Mitch Dempster", "phone": "858-275-6456", "email": "mdempster@fundloans.com", "products": [], "minFico": "660 NQ", "comp": "", "notes": ""},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Splitero Home Equity Investment (HEI)", "inArive": "", "contact": "Abraham Ordia", "phone": "619-775-2255", "email": "abraham.ordia@splitero.com", "products": [], "minFico": "", "comp": "2.50%", "notes": "LIcensed in CA, OR, WA, AZ, CO, FL New States 6.15.2026 (NV, NJ, OH, PA, SC, TN, UT, and VA)"},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Aven/TLS", "inArive": "", "contact": "Linda Whitson", "phone": "817-686-0252", "email": "linda.whitson@tlstpo.com", "products": ["Non-QM 2nd"], "minFico": "", "comp": "2.50%", "notes": ""},
  {"category": "Agency 2nds and Non-QM 2nds", "categoryLabel": "2nds (Agency & Non-QM)", "lender": "Deephaven Mortgage", "inArive": "", "contact": "Mike Wilson", "phone": "760-271-6463", "email": "mwilson@deephavenmortgage.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Fidelity Solutions", "inArive": "No", "contact": "Robert Aiello", "phone": "949-478-9838", "email": "replyinvestor@gmail.com", "products": [], "minFico": "", "comp": "", "notes": "CA, AZ, WA, NV, OR, TX, UT, CO, WY, MT, KS, OK? — CA, AZ, WA, NV, OR, TX, UT, CO, WY, MT, KS, OK?"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Val-Chris Investments", "inArive": "No", "contact": "Xavier (Javier) Saavedra", "phone": "714-655-6106", "email": "xavier@val-chris.com", "products": [], "minFico": "", "comp": "", "notes": "CA, AZ, CO, FL, HI, OK, NV, TX, WA — Out of State Footprint"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Milestone Financial, LLC* (brokers thru Center)", "inArive": "No", "contact": "Zoe Hamilton", "phone": "650-316-8970", "email": "zhamilton@milestonefinancial.net", "products": [], "minFico": "", "comp": "", "notes": "CA ONLY — OO too. 1, 2nd and 3rd up to $3m and up to 65% LTV (case by case)"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Equity Wave Lending", "inArive": "No", "contact": "Brian Baker", "phone": "949-689-8565", "email": "brian.baker@equitywavelending.com", "products": [], "minFico": "", "comp": "", "notes": "1st: AL, CA, CO, FL, GA, HI, KS, KY, MO, MT, NM, OK, TN, TX, WA, WV / 2nd: AL, CA, CO, FL (entity), GA, HI, KS, KY, MO, MT, NM, OK, TN,, WA, WV / OO States: CA, CO, FL, KY, MO, MT, NM, OK, TN, WV — Fast 50 (50% LTV no FICO/DOCS) and 75% LTV investment only. 650 FICO but will work 600-649 case by case"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Equity Wave Lending (DSCR)", "inArive": "No", "contact": "", "phone": "", "email": "", "products": [], "minFico": "", "comp": "", "notes": "DSCR States: All States EXCEPT NV, OR, UT, VT"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Velocity Mortgage Capital", "inArive": "No", "contact": "Kamran Yousefi", "phone": "949-690-3845", "email": "kyousefi@velocitymortgage.com", "products": [], "minFico": "", "comp": "", "notes": "Lumin Lending Inc is Approved in CA and all non-license required states. — family run shop. lend lesser amounts than 10M and to residential. The last deal we were involved with was 8.8M on a house in Malibu. They've also lent to a friend's primary residence...25M loan amount."},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Hankey Capital", "inArive": "No", "contact": "Priyesh Bhakta", "phone": "323-692-8443", "email": "priyesh@hankeycapital.com", "products": [], "minFico": "", "comp": "", "notes": "CA, WA, TX, GA — All States except VT, UT, and NV. Quick to respond. 680+ usually. will make exceptions if it's close"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Center Street Lending", "inArive": "No", "contact": "Jeremiah Wiedman (VP)", "phone": "949-430-0749", "email": "jwiedman@centerstreetlending.com", "products": [], "minFico": "", "comp": "", "notes": "42 States: Lower Origination Cost, Direct Lender, Private Money, New Construction, fix and flip / If you have good credit, an actual General Contractor, you can get a construction or rehab loan-minimum 650 score-negotiable"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Lima One Capital", "inArive": "No", "contact": "Josh Juroe", "phone": "949-491-4950", "email": "jjuroe@limaonecapital.com", "products": [], "minFico": "", "comp": "", "notes": "Fix & Flip, Ground Up Construction, Investement properties"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "Northwest Private Lending", "inArive": "No", "contact": "Erik Keyes", "phone": "208-789-6020", "email": "erik@nwprivatelending.com", "products": [], "minFico": "", "comp": "", "notes": "WA, OR, ID, Only First Trust deeds, go up to 65% LTV, Commercial as well"},
  {"category": "Private Money Lenders (Max 55-65% LTV)", "categoryLabel": "Private Money", "lender": "LendingXpress", "inArive": "", "contact": "Ryan Cross", "phone": "714-768-5933", "email": "ryan@lendingxpress.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Bridge Loans (Buy B4 Sell)", "categoryLabel": "Bridge (Buy-B4-Sell)", "lender": "Fly Homes", "inArive": "No", "contact": "Chris Quin", "phone": "636-547-0177", "email": "cquin@flyhomes.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Bridge Loans (Buy B4 Sell)", "categoryLabel": "Bridge (Buy-B4-Sell)", "lender": "Velocity Mortgage Capital", "inArive": "No", "contact": "Roundhouse", "phone": "949-690-3845", "email": "kyousefi@velocitymortgage.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Bridge Loans (Buy B4 Sell)", "categoryLabel": "Bridge (Buy-B4-Sell)", "lender": "Lima One Capital", "inArive": "No", "contact": "Josh Juroe", "phone": "949-491-1950", "email": "jjuroe@limaonecapital.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Bridge Loans (Buy B4 Sell)", "categoryLabel": "Bridge (Buy-B4-Sell)", "lender": "LendSure", "inArive": "No", "contact": "Aaron Winer", "phone": "858-524-3887", "email": "awiner@lendsure.com", "products": [], "minFico": "", "comp": "", "notes": "DSCR minimum FICO 660 up to 5-10 unit program. Solid Bank Statement and Asset Depletion programs. Other: Fix/Flip, Ground Up Construction, Bridge, and less than 1 YR SE program"},
  {"category": "Home Equity Conversion Mortgage (Reverse)", "categoryLabel": "Reverse (HECM)", "lender": "Longbridge Financial", "inArive": "No", "contact": "Brooke McManus", "phone": "619-917-0749", "email": "brooke.mcmanus@longbridge-financial.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Home Equity Conversion Mortgage (Reverse)", "categoryLabel": "Reverse (HECM)", "lender": "Finance of America Reverse (FAR)", "inArive": "No", "contact": "Brad Byrnes", "phone": "714-791-2229", "email": "brad.byrnes@financeofamerica.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Home Equity Conversion Mortgage (Reverse)", "categoryLabel": "Reverse (HECM)", "lender": "Wholesale Mortgage Bankers (WMB)", "inArive": "No", "contact": "Joseph Choi", "phone": "949-560-0482", "email": "joseph.choi@wmbankers.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Home Equity Conversion Mortgage (Reverse)", "categoryLabel": "Reverse (HECM)", "lender": "SmartFi", "inArive": "No", "contact": "Josh Callison", "phone": "858-358-0001 (O) / 918-855-7014 (M)", "email": "jcallison@smartfihomeloans.com", "products": [], "minFico": "", "comp": "", "notes": "FHA HECM GO TO for condos ad cheaper properties <$200K"},
  {"category": "SBA Loans", "categoryLabel": "SBA", "lender": "Newity", "inArive": "", "contact": "Harrison Weger", "phone": "872-264-7031", "email": "Hweger@newitymarket.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Home Equity Investments", "categoryLabel": "Home Equity Investment", "lender": "Point", "inArive": "", "contact": "Samuel Bjelac", "phone": "410-736-1240", "email": "sbjelac@point.com", "products": [], "minFico": "", "comp": "", "notes": "350bps / States: AZ, CA, DC, FL, HI, IN, KY, MI, MN, MO, NV, NJ, NY, OH, PA, SC, TN, UT, VA"},
  {"category": "Home Equity Investments", "categoryLabel": "Home Equity Investment", "lender": "Splitero", "inArive": "", "contact": "Abraham Ordia", "phone": "619-775-2255", "email": "abraham.ordia@splitero.com", "products": [], "minFico": "", "comp": "", "notes": ""},
  {"category": "Home Equity Investments", "categoryLabel": "Home Equity Investment", "lender": "Button Finance sign up?", "inArive": "", "contact": "George Neimann", "phone": "307-578-6842", "email": "george@buttonfinance.com", "products": [], "minFico": "", "comp": "", "notes": "[Additional notes (verify owner): up to $1MM]"},
]
